### PR TITLE
Added command to extract all packages

### PR DESCRIPTION
**Pull request by twolfson**
I am transitioning to Sublime Text 3 and like to remove built in snippets from packages. I have written `snippet-destroyer` which worked great in ST2 but I need to extract contents in order for it to work.

https://github.com/twolfson/sublime-snippet-destroyer

This PR adds an "Extract All" command to make running the 2 in succession as easy as possible. In this PR:
- Added window command to extract all packages
- Added "Extract All" command to Command Palette

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Looks good to me!

**Comment by twolfson** [comment]
Any idea when this will be landed?

**Comment by jbrooksuk** [comment]
It's my birthday today, so it seems like a good day to do it! :beers:

**Comment by twolfson** [comment]
Whoo, thanks! And happy birthday! =D :beers: :tada:

**Pull request merged**
